wbe/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import blog.forms
import blog.views

# Uncomment the next lines to enable the admin:

admin.autodiscover()

urlpatterns = [
    # Public Access
    url(r'^$', blog.views.home, name='home'),
    url(r'^contact$', blog.views.contact, name='contact'),
    url(r'^map$', blog.views.travel_map, name='map'),
    url(r'^sitemap$', blog.views.sitemap, name='sitemap'),
    url(r'^stories$', blog.views.stories, name='stories'),
    url(r'^storyfinder$', blog.views.storyfinder, name='storyfinder'),
    url(r'^action$', blog.views.action, name='action'),
    url(r'^privacy$', blog.views.privacy, name='privacy'),
    url(r'^terms', blog.views.terms, name='terms'),

    # Authentication
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register", blog.views.register, name="register"),
    path("accounts/subscribe", blog.views.subscribe, name="subscribe"),
    path("accounts/unsubscribe", blog.views.unsubscribe, name="unsubscribe"),
    path("accounts/profile", blog.views.profile, name="profile"),

    # Administration
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),

    # Manage Posts
    url(r'^manage/blog_post/$', blog.views.manage_blog_post_list,
        name='manage_blog_post_list'),
    url(r'^manage/blog_post/(?P<pk>\d+)/change/$',
        blog.views.manage_blog_post_change, name='manage_blog_post_change'),
    url(r'^manage/blog_post/(?P<pk>\d+)/upload_image/$',
        blog.views.manage_blog_post_upload_image, name='manage_blog_post_upload_image'),
    url(r'^manage/blog_post/add/$', blog.views.manage_blog_post_add,
        name='manage_blog_post_add'),
    url(r'^manage/blog_post/(?P<pk>\d+)/delete/$',
        blog.views.manage_blog_post_delete, name='manage_blog_post_delete'),
    url(r'^manage/blog_post/(?P<pk>\d+)/publish/$',
        blog.views.manage_blog_post_publish, name='manage_blog_post_publish'),
    url(r'^manage/blog_post/(?P<pk>\d+)/email_subscribers/$',
        blog.views.manage_blog_post_email_subscribers, name='manage_blog_post_email_subscribers'),
    url(r'^manage/download_database',
        blog.views.download_database, name='download_database'),
]

blog/models.py
"""
Definition of models.
"""
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# USER RELATED
from django.contrib.auth.models import User
from blog.email_helper import send_email
User._meta.get_field('email')._unique = True


class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  bio = models.TextField(max_length=500, blank=True)
  greeting = models.CharField(max_length=30, default='Hi')
  default_participants = models.CharField(max_length=120, blank=True)
  map_icon_color = models.CharField(max_length=40, default='red')
  is_subscribed_to_emails = models.BooleanField(default=False)


@receiver(post_save, sender=User)
# pylint: disable=unused-argument
def create_user_profile(sender, instance, created, **kwargs):
  if created:
    Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
# pylint: disable=unused-argument
def save_user_profile(sender, instance, **kwargs):
  instance.profile.save()

# BLOG RELATED


class BlogPost(models.Model):
  SCORE_CHOICES = [('1', 'Terrible!'), ('2', 'Meh'), ('3', 'Okay'), ('4', 'Good'),
                   ('5', 'Great!'), ('6', 'AMAZING'), ('7', 'All Time Favorite')]
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  event_date = models.DateField(default=timezone.now)
  publish_date = models.DateTimeField(default=None, blank=True, null=True)
  email_sent = models.BooleanField(default=False)
  participants = models.CharField(max_length=400, blank=True, null=True)
  loc_name = models.CharField(max_length=100, default='Name, CityOrState')
  lat = models.DecimalField(
      max_digits=10, decimal_places=4, blank=True, null=True)
  lng = models.DecimalField(
      max_digits=10, decimal_places=4, blank=True, null=True)
  title = models.CharField(max_length=250, blank=True, null=True)
  subtitle = models.CharField(max_length=400, blank=True, null=True)
  content = models.TextField(blank=True, null=True)
  score = models.CharField(
      max_length=15, choices=SCORE_CHOICES, default=4, null=True)

  def strict_validate(self):
    errors = []
    if not self.participants:
      errors.append('Participants is required')
    if not self.loc_name:
      errors.append('Location Name is required')
    if not self.title:
      errors.append('Title is required')
    if not self.subtitle:
      errors.append('Subtitle is required')
    if not self.content:
      errors.append('You must write something in the post content')
    return errors

  def publish(self):
    self.publish_date = timezone.now()
    self.save()

  def unpublish(self):
    self.publish_date = None
    self.save()

  def send_email(self):
    subscribed_users = Profile.objects.filter(is_subscribed_to_emails=True)
    subject = f'''New Post: {self.title}!'''
    body = f'''
<p>We have a new story!<br/>
Check it out :)</p>
<p>
  <b>{self.title}</b><br/>
  <i>{self.subtitle}</i><br/>
  <a href='https://wevebeeneverywhere.com/stories?id={self.id}'>Click here to read the story!</a>
</p>
<p>Thanks for reading,<br/>
Nathan and Molly</p>
<p>Want to change how you receive these emails?<br/>
You can <a href='https://wevebeeneverywhere.com/accounts/profile'>update your preferences</a> or <a href='https://wevebeeneverywhere.com/accounts/unsubscribe'>unsubscribe from this list</a>.</p>
'''
    for subscribed_user in subscribed_users:
      recipient = subscribed_user.user.email
      print('Sending email to ' + recipient)
      send_email(recipient, subject, body)
    self.email_sent = True
    self.save()
    return len(subscribed_users)

  def comment_count(self):
    obj_pk = self.id
    return PostInteraction.objects.filter(type='comment', post_id=obj_pk).count()

  def like_count(self):
    obj_pk = self.id
    return PostInteraction.objects.filter(type='like', post_id=obj_pk).count()

  def get_comments(self):
    obj_pk = self.id
    return PostInteraction.objects.filter(type='comment', post_id=obj_pk).order_by('-interaction_date')


class MediaItem(models.Model):
  MEDIA_TYPES = [
      ('picture', 'picture'),
      ('video', 'video')
  ]
  ALLOWED_FILE_EXTENSIONS = [
      ('jpg', 'png'),
      ('png', 'jpg'),
      ('png', 'jpeg'),
  ]
  post_id = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
  media_type = models.CharField(
      max_length=10, choices=MEDIA_TYPES, default=1)
  caption = models.CharField(max_length=250)
  file_name = models.UUIDField()
  file_extension = models.CharField(
      max_length=10, choices=ALLOWED_FILE_EXTENSIONS, default=1)
  source_url = models.CharField(max_length=400)
  source_image_file = models.ImageField(upload_to='post_uploads')


class PostInteraction(models.Model):
  type = models.CharField(max_length=100)
  user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
  post_id = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
  interaction_date = models.DateTimeField(default=timezone.now)
  content = models.TextField()

blog/views.py
"""
Definition of views.
"""

import uuid
from datetime import datetime

from azure.storage.blob import BlobServiceClient, __version__
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import (login_required,
                                            permission_required,
                                            user_passes_test)
from django.contrib.auth.models import User
from django.core.files import File
from django.http import HttpRequest, JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from blog.forms import (BlogPostFilterForm, BlogPostForm, ProfileForm,
                        RegisterForm, SubscribeForm, UnsubscribeForm, UserForm)
from blog.models import BlogPost, MediaItem, PostInteraction

import environment

# CONSTANTS
UPPER_BLOG_POST_FORM_FIELDS = [
    'title',
    'subtitle',
    'participants',
    'loc_name',
    'lat',
    'lng',
    'score',
    'event_date',
    'publish_date',
]

LOWER_BLOG_POST_FORM_FIELDS = [
    'content',
]

# HELPER FUNCTIONS


def getposts(request, topx=None, sort='-publish_date', post_id='all', author='all', published_only=True):
  posts = BlogPost.objects.all().order_by(sort).defer('content')

  if str(post_id) != 'all':
    posts = posts.filter(id=post_id)

  if str(author) != 'all':
    posts = posts.filter(author=author)

  if published_only:
    posts = posts.filter(publish_date__lte=datetime.now())

  if isinstance(topx, int):
    posts = posts[:topx]
  return posts


def action(request):
  request_type = request.GET.get('type', '')
  target = request.GET.get('target', '')
  details = request.GET.get('details', '')
  current_user = None
  if request.user.is_authenticated:
    current_user = request.user
  if request_type == "like":
    newlike = PostInteraction(
        user_id=current_user,
        post_id=getposts(request, post_id=target)[0],
        type=request_type)
    newlike.save()
    return redirect('/stories?id=' + target)
  elif request_type == "comment":
    comment = PostInteraction(
        user_id=request.user,
        post_id=getposts(request, post_id=target)[0],
        content=details,
        type=request_type)
    comment.save()
    return redirect('/stories?id=' + target)
  elif request_type == "deletecomment":
    comment = PostInteraction(
        id=target,
        content=details,
        type='comment')
    comment.delete()
    return redirect('/stories?id=' + details)
  else:
    raise Exception('Unknown Request Type')

# PUBLIC PAGES


def home(request):
  assert isinstance(request, HttpRequest)
  story_count = getposts(request).count()
  return render(
      request,
      'app/views/index.html',
      {
          'title': 'Home',
          'description': 'Explore everywhere with us!',
          'og_type': 'website',
          'og_image': 'http://i.imgur.com/wISv7LI.png',
          'story_count': story_count,
      }
  )


def travel_map(request):
  assert isinstance(request, HttpRequest)
  posts = getposts(request, sort='publish_date')
  # Only take posts with lat/lng to not break map
  posts = posts.filter(lat__isnull=False)
  posts = posts.filter(lng__isnull=False)
  return render(
      request,
      'app/views/map.html',
      {
          'title': 'Map',
          'description': 'Map of our adventures!',
          'og_type': 'website',
          'og_image': 'http://i.imgur.com/wISv7LI.png',
          'posts': posts,
          'google_maps_api_key': environment.GOOGLE_MAPS_API_KEY,
      }
  )


def stories(request):
  assert isinstance(request, HttpRequest)
  # page basics
  post_id = request.GET.get('id', 'all')
  topx = request.GET.get('topx', 15)
  title = 'Stories'
  description = 'Chronicling the adventures of Molly and Nathan as we venture across the world.'
  og_type = 'website'
  post_list = getposts(request, topx=topx)
  og_image = 'http://i.imgur.com/wISv7LI.png'

  # get main post
  if post_id == 'all':
    posts = getposts(request)[0:5]
  else:
    posts = getposts(request, post_id=post_id)

  # if only one post meets criteria, optimize seo
  if posts.count() == 1:
    title = posts[0].title
    description = posts[0].subtitle
    og_type = 'article'
    try:
      og_image = posts[0].content.split('<img')[1].split('src="')[
          1].split('"')[0]
    # pylint: disable=broad-except
    except Exception:
      pass

  posts_with_liked = []

  for post in posts:
    if request.user.is_authenticated:
      posts_with_liked.append((
          post,
          PostInteraction.objects.all().filter(
              type='like', user_id=request.user, post_id=post.id)
      ))
    else:
      posts_with_liked.append((post, False))

  return render(
      request,
      'app/views/stories.html',
      {
          'title': title,
          'description': description,
          'og_type': og_type,
          'og_image': og_image,
          'post_list': post_list,
          'posts': posts_with_liked,
          'current_user': request.user,
      }
  )


def storyfinder(request):
  assert isinstance(request, HttpRequest)

  title = 'Story Finder'
  description = 'Chronicling the adventures of Molly and Nathan as we venture across the world.'
  og_type = 'website'
  og_image = 'http://i.imgur.com/wISv7LI.png'

  post_list = getposts(request)
  form = BlogPostFilterForm(request.GET)
  return render(
      request,
      'app/views/storyfinder.html',
      {
          'title': title,
          'description': description,
          'og_type': og_type,
          'og_image': og_image,
          'post_list': post_list,
          'form': form
      }
  )


def sitemap(request):
  assert isinstance(request, HttpRequest)
  post_list = getposts(request)
  return render(
      request,
      'app/views/sitemap.html',
      {
          'post_list': post_list,
      }
  )

# POST MANAGEMENT
# Manage Post List


@permission_required('blog_post.add_blog_post')
def manage_blog_post_list(request):
  assert isinstance(request, HttpRequest)
  post_list = getposts(request, author=request.user, published_only=False)

  return render(
      request,
      'app/views/manage_blog_post_list.html',
      {
          'post_list': post_list,
          'post_count': len(post_list),
      }
  )

# Add Post


@permission_required('blog_post.add_blog_post')
def manage_blog_post_add(request):
  assert isinstance(request, HttpRequest)
  post = BlogPost(
      author=request.user
  )
  post.save()
  return redirect('manage_blog_post_change', pk=post.pk)

# Change Post


@permission_required('blog_post.change_blog_post')
def manage_blog_post_change(request, pk):
  assert isinstance(request, HttpRequest)
  post = get_object_or_404(BlogPost, pk=pk)
  if request.user == post.author:
    if request.method == "POST":
      form = BlogPostForm(request.POST, instance=post)
      if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect(manage_blog_post_list)
    else:
      form = BlogPostForm(instance=post)
    return render(
        request,
        'app/views/manage_blog_post.html',
        {
            'blog_post_form': form,
            'upper_fields': UPPER_BLOG_POST_FORM_FIELDS,
            'lower_fields': LOWER_BLOG_POST_FORM_FIELDS,
            'post': post,
            'title': 'Edit Post: ' + (post.title or 'Untitled')
        }
    )
  else:
    return redirect('manage_blog_post_list')

# Upload Image to Post


@permission_required('blog_post.change_blog_post')
def manage_blog_post_upload_image(request, pk):
  assert isinstance(request, HttpRequest)
  if not request.method == 'POST':
    raise Exception('Invalid HTTP Method. POST is Required')
  post = get_object_or_404(BlogPost, pk=pk)
  file = request.FILES['upload']
  file_ext = file.name.split('.')[-1]
  file_name = f'''{uuid.uuid4()}.{file_ext}'''
  source_url = f'''https://wevebeeneverywhere.blob.core.windows.net/media/{ file_name }'''
  # Create a blob client using the local file name as the name for the blob
  connect_str = environment.AZURE_STORAGE_CONNECTION_STRING
  blob_service_client = BlobServiceClient.from_connection_string(connect_str)
  blob_client = blob_service_client.get_blob_client(
      container='media', blob=file_name)

  print("\nUploading to Azure Storage as blob:\n\t" + file_name)

  # Upload the created file
  with file.open() as data:
    blob_client.upload_blob(data)
  data = {
      'url': source_url
  }
  # Save Media Item to Database
  media_item = MediaItem()
  media_item.post_id = post
  media_item.media_type = 'picture'
  media_item.caption = ''
  media_item.file_name = file_name.replace('.' + file_ext, '')
  media_item.file_extension = file_ext.lower()
  media_item.source_url = source_url
  media_item.save()
  return JsonResponse(data)

# Delete Post


@permission_required('blog_post.change_blog_post')
def manage_blog_post_delete(request, pk):
  assert isinstance(request, HttpRequest)
  post = get_object_or_404(BlogPost, pk=pk)
  if request.user == post.author:
    post.delete()
  return redirect('manage_blog_post_list')

# Email Subscribers


@permission_required('blog_post.change_blog_post')
def manage_blog_post_email_subscribers(request, pk):
  assert isinstance(request, HttpRequest)
  post = get_object_or_404(BlogPost, pk=pk)
  if request.user == post.author:
    emails_sent = post.send_email()
    messages.success(request, "Emailed " +
                     str(emails_sent) + " subscriber(s)")
  return redirect('manage_blog_post_list')

# Publish Post


@permission_required('blog_post.change_blog_post')
def manage_blog_post_publish(request, pk):
  assert isinstance(request, HttpRequest)
  post = get_object_or_404(BlogPost, pk=pk)
  if request.user == post.author:
    errors = post.strict_validate()
    if len(errors) > 0:
      messages.error(
          request, "Unable to publish. Please correct these errors: " + ', '.join(errors))
    else:

blog/templates/app/manage_blog_post.html
{% extends "app/layout.html" %}

{% block content %}

<style>
    input, select{
        width: 350px;
        max-width: 350px;
    }
    textarea {
        width:550px;
        max-width: 550px;
    }

    @media (max-width: 768px) {
        input, select, textarea {
            width: 350px;
        }
        form{
            padding:0px;
        }
    }
</style>

<div style="max-width: 650px; margin:auto; margin-top:30px; float:left;">
    <a href="/manage/blog_post">Back to post list</a>
    <h2 style="margin-bottom:10px;">{{ title }}</h2>
    <ul style="margin-bottom:20px;">
        <li>Current User: {{ request.user }}</li>
        <li>Map Icon Color: {{ user.profile.map_icon_color }}</li>
        {% if request.user.is_staff %}
        <li><a href="/admin/app/profile/{{ request.user.id }}/change/" target="_blank">Edit Profile</a></li>
        {% else %}
        <li>Contact site staff to help change you profile.</li>
        {% endif %}
    </ul>

    <br />
    <a href="#" onclick="$('#code_shortcuts').toggle();">Show/Hide Code Shortcuts</a>
    <br />
    <div id="code_shortcuts" style="display:none;">
        <h4>Image Code with Caption</h4>
        <p>To use: <i>Copy and paste, then replace the caption and "src" attribute</i></p>
        <pre><code>&lt;div class="img_holder"&gt;&lt;div class="img_caption"&gt;CAPTION GOES HERE&lt;/div&gt;&lt;img style="width:100%; max-width:350px;" src="http://i.imgur.com/sVg4kw3.jpg"&gt;&lt;/div&gt;</code></pre>
        <h4>Image Code without Caption </h4>
        <p>To use: <i>Copy and paste, then replace the "src" attribute</i></p>
        <pre><code>&lt;div class="img_holder"&gt;&lt;img style="width:100%; max-width:350px;" src="http://i.imgur.com/sVg4kw3.jpg"&gt;&lt;/div&gt;</code></pre>
    </div>

    <form style="margin-top:20px; background-color:whitesmoke; padding: 50px;" action="." method="post">
        {% csrf_token %}
        {% for field in BlogPostForm %}
            <div class="form-label">{{ field.label_tag }}</div> <div style="min-width:200px;"class="form-field">{{ field }}</div>
            <br style="clear:both;"/>    
            <div style="color:red;">{{ field.errors }}</div>
            <br style="clear:both;"/>
        {% endfor %}
        {{ form.non_field_errors }}
        <input type="submit" value="Submit" />
    </form>
</div>

<style>

    :target:before {
        content:"";
        display:block;
        height:50px; /* fixed header height*/
        margin:-50px 0 0; /* negative fixed header height */
        }

    .story_header{
        text-align:center;
    }

    .story_date, .story_location, .story_author, .story_links {
        margin-top: 0px;
        margin-bottom: 0px;
    }

    .story_post{
        background-color: whitesmoke;
        margin-top:10px;
        padding:50px;
    }

    .story_post:hover{
        border: 1px solid #bbb;
    }

    .story_content{
        margin:auto;
        padding-top: 10px;
        max-width: 750px;
    }

    .story_content > p {
        text-align: justify;
        margin-bottom: 20px;
    }

    img, iframe{
       display:block;
       margin: 0px auto 30px !important;
       border: none;
    }

    .img_caption {
        background-color: white;
        color: #111;
        text-align:center;
        padding: 15px
    }
    .img_holder {
        background-color: #ddd;
    }

    #linkcopied {
      position: fixed;
      top: 50%;
      left: 50%;
      display:none;
      background-color: white;
      padding:50px 100px;
      /* bring your own prefixes */
      transform: translate(-50%, -50%);
    }

    @media (max-width: 768px) {
    .story_post{
        padding: 15px;
    }
}
</style>

<h2 style="max-width:550px; margin-left:50px;margin-top:70px; float:left;">Post Preview</h2>
<div style="max-width: 550px; margin-left:50px; margin-top:30px; float:left; max-height:1050px; overflow:auto;" id="preview">
    <div class="story_post">
        <div class ="story_header">     
            <h1 id='title_preview'></h1>
            <h3 id="subtitle_preview"></h3>
            <p class="story_date"><span id="participants_preview"></span> traveling on <span id="event_date_preview"></span></p>
            <p class="story_location">Location: <span id="loc_name_preview"></span></p>
            <p class="story_author">Written by: {{ request.user.first_name }} {{ request.user.last_name }}</p>
        </div>
        <hr style="border-color: white;"/>
        <div class="story_content">
            <span id="content_preview"></span>
            
            <div style="background-color:#ddd; margin:auto; padding:15px;">
                Social icons and sharing links go here.
            </div>
        </div>
    </div>
</div>

<br style="clear:both;" />

<script>
    $(document).ready(function () {
        $(document).keyup(function (e) {
            generate_preview();
        })
    });

    generate_preview();

    function generate_preview() {

        var title = $('#id_title').val()
        var subtitle = $('#id_subtitle').val()
        var participants = $('#id_participants').val()
        var event_date = $('#id_event_date').val()
        var loc_name = $('#id_loc_name').val()
        var content = $('#id_content').val()
        
        $('#title_preview').html(title);
        $('#subtitle_preview').html(subtitle);
        $('#participants_preview').html(participants);
        $('#event_date_preview').html(event_date);
        $('#loc_name_preview').html(loc_name);
        $('#content_preview').html(content);
        
    }
</script>
{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

blog/templates/app/manage_blog_post_list.html
{% extends "app/layout.html" %}

{% block content %}

<div style="padding:20px;">
    
    <h3>Posts by {{ request.user }}. <a href="/manage/blog_post/add">Add Post</a></h3>
    <table class="custom sortable">
        <tr>
            <th>Event Date</th>
            <th>Published On</th>
            <th>Title</th>
            <th>Subtitle</th>
            <th></th>
            <th></th>
        </tr>
    {% for post in post_list %}
        <tr>
            <td>
                {{post.event_date}}
            </td>
            <td>
                {{post.publish_date}}
            </td>
            <td>
                 {{ post.title }}
            </td>
            <td>
                {{ post.subtitle }}
            </td>
            <td>
                <a href="/manage/blog_post/{{ post.id }}/change" >edit </a>
            </td>
            <td>
                <a href="/manage/blog_post/{{ post.id }}/delete" class="confirmation">delete </a>
            </td>
        </tr>
    {% endfor %}
    </table>
</div>
{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

blog/templates/app/map.html
{% extends "app/layout.html" %}

{% block content %}
    <style>
        #pagecontent {
            min-width: 100%;
            padding: 0px;
        }
    </style>
    <div id="map" style="position:fixed; top: 0; left:0; height:90vh;"></div>
    <script>

    function pinSymbol(color) {
    return {
        path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z M -2,-30 a 2,2 0 1,1 4,0 2,2 0 1,1 -4,0',
        fillColor: color,
        fillOpacity: .75,
        strokeColor: 'gainsboro',
        strokeWeight: 1,
        scale: 1.2,
   };
}

        function initMap() {
            var center = {lat: 20, lng: -55};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 2,
              center: center,
              gestureHandling: 'greedy',
            });
            
            i = 0;
            function addmarker(color, lat, lng, participants, content) {
                i += 1;
                var infowindow = new google.maps.InfoWindow({
                    content: content
                });
            
                var marker = new google.maps.Marker({
                    position: { lat: lat, lng: lng },
                    map: map,
                    icon: pinSymbol(color),
                    title: 'click for more!',
                    zIndex: i
                });

                marker.addListener('click', function() {
                    infowindow.open(map, marker);
                });
            }

            {% for post in posts %}
                addmarker('{{ post.author.profile.map_icon_color }}', {{ post.lat }}, {{ post.lng }}, '{{ post.participants }}', '<h3>{{ post.title }}</h3><h4>{{ post.subtitle }}</h4><p>Author: <span style="font-weight:bold;color:{{ post.author.profile.map_icon_color }};">{{post.author.first_name}} {{post.author.last_name}}</span> <br/>Travelers: {{ post.participants }}<br />Date: {{ post.event_date }}<br />Location: {{ post.loc_name }}<br /><a href="/stories?id={{ post.id }}">Read the story!</a>');
            {% endfor %}
        
        }
        
    <!-- {{ post.author.first_name }} -->
    </script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCFPqo30Xeib3nToxMs2r36JYRgVipJM24&callback=initMap">
    </script>
        
    

{% endblock %}

blog/templates/app/storyfinder.html
{% extends "app/layout.html" %}

{% block content %}

<script>
function getUrlVars()
{
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
            hash = hashes[i].split('=');                        
            vars[hash[0]] = hash[1];
    }
    return vars;
}

var url_vars = getUrlVars();
for(var i in url_vars)
{
    $('#' + i).val(url_vars[i]);
}   
</script>

<style>
    .leftformsection {
        width: 200px;
        float:left;
    }
    input {
        width:150px;
    }
</style>

<div style="padding:20px; min-width:1000px; background-color:white;">
    <h3>Posts filters.</h3>
    <p>Click on a column to sort! Title links to story.</p>

<form action="/storyfinder" method="get" style="padding:20px; background-color:whitesmoke; margin-bottom:20px; display:none;">
    <div><div class="leftformsection">Published Between:</div> <input type="date" id="p_min" name="p_min" /> and <input type="date" id="p_max" name="p_max" /></div>
    <div><div class="leftformsection">Happened Between:</div> <input type="date" id="h_min" name="h_min" /> and <input type="date" id="h_max" name="h_max" /></div>
    <div><div class="leftformsection">Score Between:</div> <input type="number" id="s_min" name="s_min" /> and <input type="number" id="s_max" name="s_max" /></div>
    <div><div class="leftformsection">Author:</div> <input type="text" id="author" name="author" /> </div>
    <div><div class="leftformsection">Location:</div> <input type="text" id="loc" name="loc" /> </div>
    <input type="submit" value="Submit" />
</form>

    <table class="custom sortable" style="width:100%; min-width:600px;">
        <tr>
            <th>Event Date</th>
            <th>Published On</th>
            <th>Title</th>
            <th>Subtitle</th>
            <th>Location</th>
            <th>Score</th>
            <th>Author</th>
            <th>Cheers</th>
            <th>Comments</th>
        </tr>
    {% for post in post_list %}
        <tr>
            <td>
                {{post.event_date|date:"Y/m/d"}}
            </td>
            <td>
                {{post.publish_date|date:"Y/m/d"}}
            </td>
            <td>
                 <a href="/stories?id={{ post.id }}">{{ post.title }}</a>
            </td>
            <td>
                {{ post.subtitle }}
            </td>
            <td>
                {{ post.loc_name }}
            </td>
            <td>
                <span style="display: none;">{{ post.score }}</span> {{ post.get_score_display }}
            </td>
            <td>
                {{ post.author.first_name }} {{ post.author.last_name }} 
            </td>
            <td>
                {{ post.like_count }} 
            </td>
            <td>
                {{ post.comment_count }} 
            </td>
        </tr>
    {% endfor %}
    </table>
</div>


{% endblock %}